"""add company_data table

Revision ID: 0c09354fedd8
Revises: 410811fb2a19
Create Date: 2026-01-18 18:01:32.678812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c09354fedd8'
down_revision = '410811fb2a19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date_parse', sa.Date(), nullable=False),
    sa.Column('cms', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('external_js', sa.Text(), nullable=True),
    sa.Column('social_links', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('companies', 'framework')
    op.drop_column('companies', 'language')
    op.drop_column('companies', 'social_links')
    op.drop_column('companies', 'external_js')
    op.drop_column('companies', 'cms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('cms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('external_js', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('social_links', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('framework', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('companies_data')
    # ### end Alembic commands ###

